version: 2.1

executors:
  node-executor:
    working_directory: ~/vendor-contract-mgmt-client
    docker:
      - image: cimg/node:17.2.0

jobs:
  lint-project:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Lint Project
          command: npm lint
  
  test-project:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Test Project
          command: npm test

workflows:
  test-lint-project:
    jobs:
      - lint-project
      - test-project
  
