version: 2.1

executors:
  node-executor:
    working_directory: ~/vendor-contract-mgmt-client
    docker:
      - image: cimg/node:17.2.0
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  lint-project:
    executor: node-executor
    steps:
      - checkout
      - node/install
      - run:
          name: Lint Project
          command: >
            npm install
            npm run lint
  
  test-project:
    executor: node-executor
    steps:
      - checkout
      - node/install
      - run:
          name: Test Project
          command: >
            npm install 
            npm run test
  
  deploy-s3:
    executor: node-executor
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - run:
        name: Build Application
        command: >
          npm i @angular/cli
          ng build --configuration=production
    - aws-s3/sync:
        aws-region: AWS_N_VA_REGION
        aws-access-key-id: AWS_ACCESS_KEY_ID_S3
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY_S3
        from: ./dist/vendor-contract-mgmt-client
        to: s3://vendor-contract-mgmt-client

workflows:
  test-lint-project:
    jobs:
      - lint-project:
          filters:
            branches:
              ignore:
                - /main/
      - test-project:
          filters:
            branches:
              ignore:
                - /main/
  deploy-production:
    jobs:
      - deploy-s3:
          context:
            - AWS
          filters:
            branches:
              only: /main/