version: 2.1

executors:
  node-executor:
    working_directory: ~/vendor-contract-mgmt-client
    docker:
      - image: cimg/node:17.2.0
orbs:
  node: circleci/node@5.0.2

jobs:
  lint-project:
    executor: node-executor
    steps:
      - checkout
      - node/install
      - run:
          name: Lint Project
          command: npm run lint
  
  test-project:
    executor: node-executor
    steps:
      - checkout
      - node/install
      - run:
          name: Test Project
          command: npm run test

workflows:
  test-lint-project:
    jobs:
      - lint-project:
          filters:
            branches:
              ignore:
                - /main/
      - test-project:
          filters:
            branches:
              ignore:
                - /main/
